### PR TITLE
FIX Format.cmake dir path in cmake-format args (#26)

### PR DESCRIPTION
**Pull request by TheLongRunSmoke**
Add small fix for [this issue](https://github.com/TheLartians/Format.cmake/issues/26).

### CODE REVIEW

**Comment by TheLartians** [comment]
Hey, thanks for finding and fixing this bug! Could you run [cmake-format](https://github.com/cheshirekow/cmake_format) to style the code changes as well?

For example, the following should work:

```bash
cmake-format ./CMakeLists.txt > ./CMakeLists.txt 
cmake-format ./cmake-format.cmake > ./cmake-format.cmake
```

**Review by TheLartians — APPROVED** [review]
Thanks for the changes!

**Comment by TheLongRunSmoke** [comment]
Done. `cmake-format ./cmake-format.cmake -o ./cmake-format.cmake` explicitly write to a file is clearer way than redirecting stdout, in my opinion.

**Comment by TheLartians** [comment]
Good point, I agree that it's cleaner that way. 
The fix is realised in `v1.7.2`!

**Pull request merged**
