### PR TITLE
Allow specifying extra arguments to CMake format

### PR DESCRIPTION
**Pull request by krypty**
Hello,

The configuration format is described here: https://github.com/cheshirekow/cmake_format#configuration

Please tell if I got any wrong with regards to contributing to this project.

### CODE REVIEW

**Review by TheLartians — COMMENTED** [review]
Thanks for the PR! I'm a bit unsure about this one, as cmake-format already provides an implicit way to add config files using the file path, which for example is it convenient to specify different configs for different directories:

> Otherwise, cmake-format will search the ancestry of each infilepath looking for a configuration file to use. If no configuration file is found it will use sensible defaults.
A automatically detected configuration files may have any name that matches \.?cmake-format(.yaml|.json|.py).

But I do see how it can be useful extra arguments to the cmake-format command. How instead we add a more generic option `CMAKE_FORMAT_EXTRA_ARGS` to allow users to provide arbitrary extra arguments to the CMake format executable?

**Comment by krypty** [comment]
Sure good idea, I will come back with the more generic proposition you made i.e. `CMAKE_FORMAT_EXTRA_ARGS`.

**Comment by krypty** [comment]
OK, I think I got it right. Tell me if that's not the case :) Should we change the PR title?

**Review by TheLartians — APPROVED** [review]
Looks great, thanks for the changes! I've gone ahead and updated the PR title. ;-)

**Pull request merged**
